services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - faiss_index:/app/data/vector_db_faiss  # FAISS specific volume
      - vector_db_data:/app/data/vector_db     # Keep ChromaDB for backup
      - model_data:/app/data/models
      - log_data:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - ../env/.env
      - ../env/.env.local
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_SHEETS_ID=${GOOGLE_SHEETS_ID}
      - CHAT_CONCURRENCY=8
      - CHUNK_SIZE=1000
      - CHUNK_OVERLAP=200
      - DEBUG=0
      - VECTOR_DB_TYPE=faiss
      - FAISS_INDEX_PATH=/app/data/vector_db_faiss
      - FAISS_DIMENSION=1536  # OpenAI embedding dimension
      - FAISS_METRIC=inner_product
      - FAISS_NPROBE=8  # Number of clusters to probe
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  faiss_index:     # Persistent volume for FAISS indexes
    driver: local
  vector_db_data:  # Persistent volume for vector database (ChromaDB backup)
    driver: local
  model_data:      # Persistent volume for downloaded models
    driver: local
  log_data:        # Persistent volume for logs
    driver: local
